project_directory: ''
output_dir: ''

# Training parameters
batch_size: 32
initial_lr: 0.000001
max_lr: 0.00001
step_size: 20
N_epochs: 100
patience: 10
q_min: 0.1
tB: 0.1
tD: 0.25
ev: 0
ev_n: 10 

# GravNet model parameters
N_grav_layers: 12
N_neighbors: 10
N_filters: 256