project_directory: ''
output_dir: ''

# Training parameters
batch_size: 32
initial_lr: 0.0001
max_lr: 0.001
step_size: 20
N_epochs: 100
patience: 10
q_min: 0.1
tB: 0.1
tD: 0.25
ev: 0
ev_n: 3
train_size: 5000  # Optional: Use only the first 5000 examples for training
test_size: 2000   # Optional: Use only the first 2000 examples for testing
# GravNet model parameters
N_grav_layers: 2
N_neighbors: [8,8]
N_filters: 64